---
- name: Create directory for SSL certificates
  file:
    path: /etc/ssl/private/
    state: directory
    owner: root
    group: ssl-cert
    mode: 0710

- name: Copy the SSL certificate
  copy:
    src: "{{ ssl_certfile }}"
    dest: /etc/ssl/private/teamwire-backend.crt
    mode: 0640
  when: ssl_certfile is defined

- name: Copy the SSL key
  copy:
    src: "{{ ssl_keyfile }}"
    dest: /etc/ssl/private/teamwire-backend.key
    mode: 0640
  when: ssl_keyfile is defined

- name: Generate a new Diffie-Hellman group
  command: /usr/bin/openssl dhparam -out /etc/ssl/private/dhparams.pem 2048
  when: ssl_certfile is defined and ssl_keyfile is defined
  args:
    creates: /etc/ssl/private/dhparams.pem

- name: Check SSL pair is valid (hasn't expired, modern algorithm and key matches certificate)
  openssl_certificate:
    path: /etc/ssl/private/teamwire-backend.crt
    privatekey_path: /etc/ssl/private/teamwire-backend.key
    provider: assertonly
    signature_algorithms:
      - sha224WithRSAEncryption
      - sha256WithRSAEncryption
      - sha384WithRSAEncryption
      - sha512WithRSAEncryption
      - sha224WithECDSAEncryption
      - sha256WithECDSAEncryption
      - sha384WithECDSAEncryption
      - sha512WithECDSAEncryption
    has_expired: False
  when: ssl_certfile is defined
  run_once: true

- name: Re-use sockets in TIME_WAIT state for new connections
  sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1
    state: present

- name: Ensure netfilter can handle a sufficient amount of connections
  sysctl:
    name: net.nf_conntrack_max
    value: 65536
    state: present

- name: Increase number of socket connection backlog
  sysctl:
    name: net.core.somaxconn
    value: 1024
    state: present
    reload: yes

- include: centos.yml
  when: ansible_distribution|lower == "centos"

- include: non_centos.yml
  when: ansible_distribution|lower != "centos"

- name: Start and enable nginx
  service:
    name: nginx
    state: started
    enabled: true

- include: single.yml
  when: "'frontend_servers' not in groups"

- include: cluster.yml
  when: 
    - "'frontend_servers' in groups"
    - ansible_distribution | lower != "centos"

- name: die
  fail:
    msg: "died {{ ansible_distribution }}"

