---
- name: Install Redis
  apt: name={{item}} state=present
  with_items:
  - redis-tools
  - python-redis
  when: ansible_distribution|lower != "centos"

- name: Install Redis (CentOS)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - redis
  - python-redis
  when: ansible_distribution|lower == "centos"

# See http://redis.io/topics/faq for details
- name: Enable vm.overcommit_memory for Redis
  sysctl:
    name: vm.overcommit_memory
    value: 1
    state: present
    reload: yes

- name: Increase number of socket connection backlog
  sysctl:
    name: net.core.somaxconn
    value: 1024
    state: present
    reload: yes

- include: single_non_centos.yml
  when:
    - "'redis_servers' not in groups"
    - ansible_distribution|lower != "centos"

- include: single_centos.yml
  when:
    - "'redis_servers' not in groups"
    - ansible_distribution|lower == "centos"

- include: cluster.yml
  when: 
    - "'redis_servers' in groups"
    - ansible_distribution|lower != "centos"
