---
- name: Install Redis server
  apt: name=redis-server state=present

- name: Configure Redis to listen on all interfaces
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: ^bind\s+127.0.0.1
    line: "bind 0.0.0.0"
    backrefs: yes
  notify: restart redis

- name: Configure password for Redis
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: ^(# )+requirepass
    line: "requirepass {{ redis_pass }}"
    backrefs: yes
  when: redis_pass is defined
  notify: restart redis

- name: Start and enable Redis server
  service:
    name: redis-server
    state: started
    enabled: yes
