---
- name: Ensure mysql_root_password is configured before installing the Database
  fail:
    msg: "MySQL root password is not defined. Please check the configuration file"
  when: config_done is defined and mysql_root_password is defined and mysql_root_password == None

- name: Check if installing a database cluster
  set_fact:
    galera_cluster: True
  when: '"database_servers" in groups and groups["database_servers"] | length > 1'

- include: centos.yml
  when: ansible_distribution|lower == "centos"

- include: non_centos.yml
  when: ansible_distribution|lower != "centos"

# Make sure MariaDB is restarted before the database is created, otherwise
# the configured defaults are not used.
- meta: flush_handlers

- name: Set password for MariaDB root user
  mysql_user:
    name: root
    password: "{{mysql_root_password}}"
  when: mariadb_initial_installation

- name: Remove anonymous user
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{mysql_root_password}}"

- name: Remove test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{mysql_root_password}}"

- name: Set password for the other MariaDB root users
  mysql_user:
    name: root
    password: "{{mysql_root_password}}"
    host: "{{item}}"
    login_user: root
    login_password: "{{mysql_root_password}}"
  when: mysql_root_password is defined and (galera_cluster is not defined or inventory_hostname == groups['database_servers'][0])
  with_items:
    - 127.0.0.1
    - ::1
    - "{{external_hostname|default()}}"

- name: Create Teamwire database
  mysql_db:
    name: "{{ teamwire_db_name | default('teamwire') }}"
    state: present
    login_user: root
    login_password: "{{mysql_root_password}}"
  when: galera_cluster is not defined or inventory_hostname == groups['database_servers'][0]

- name: Create Teamwire database user
  mysql_user:
    name: "{{ teamwire_db_user | default('teamwire') }}"
    host: "%"
    password: "{{teamwire_db_password}}"
    priv: "{{ teamwire_db_name | default('teamwire') }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{mysql_root_password}}"
  when: config_done is defined and (galera_cluster is not defined or inventory_hostname == groups['database_servers'][0])

- name: die
  fail:
    msg: died 
