---
- name: Check Ansible version
  fail:
    msg:
      - "Ansible >= 2.4.2 is required"
  when:
    - ansible_version['major'] < 2
    - ansible_version['minor'] < 4
    - ansible_version['revision'] < 2

- name: Check if installing offline
  stat: path=/etc/offline_installation
  register: offline_mode

- include: centos.yml
  when: ansible_distribution|lower == "centos"

- include: non_centos.yml
  when: ansible_distribution|lower != "centos"

- name: Install python-pyOpenSSL version {{ required_pyopenssl_version }}
  pip: 
    name: pyopenssl
    version: "{{ required_pyopenssl_version }}"
    extra_args: '{{ "--proxy="+http_proxy if http_proxy is defined else omit }}'

- name: Write the Postfix configuration file
  template:
    src: postfix-main.cf.j2
    dest: /etc/postfix/main.cf
  when: config_done is defined
  notify: restart postfix

- name: Write the Postfix password file
  template:
    src: postfix-passwd.j2
    dest: /etc/postfix/sasl/passwd
    mode: 0600
  when: config_done is defined
  notify: rebuild postfix passwd map

- name: Give root a speaking name
  when: config_done is defined
  user:
    name: root
    comment: "root@{{ external_hostname }}"

- name: Disable SSH password logins
  when: ssh_disable_passwords is defined and ssh_disable_passwords
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^#?PasswordAuthentication
    line: "PasswordAuthentication no"
  notify: reload sshd

- name: Enable SSH password logins
  when: ssh_disable_passwords is not defined or not ssh_disable_passwords
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^#?PasswordAuthentication
    line: "PasswordAuthentication yes"
  notify: reload sshd

- name: Disable DNS lookup on SSH login
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "UseDNS no"
  notify: reload sshd

- name: Check out the teamwire/platform git repository
  git:
    repo: https://github.com/teamwire/platform.git
    depth: 1
    dest: /home/teamwire/platform
    update: no
  notify: fix ownership of git checkout
  when: groups['all'] | length() == 1

- stat: path=/home/teamwire/platform/ansible/group_vars/all
  register: config_file

- name: Secure permissions of Ansible configuration file
  file:
    path: /home/teamwire/platform/ansible/group_vars/all
    state: file
    mode: 0600
    owner: teamwire
    group: teamwire
  when: config_file.stat.exists

- name: Create SSH keys for the teamwire user
  user:
    name: teamwire
    generate_ssh_key: yes
  when: config_done is defined

- name: Send all logs to loghost or remote syslog servers
  when: "'loghost' in groups or syslog_servers is defined"
  template:
    src: 30-remote-logging.conf.j2
    dest: /etc/rsyslog.d/30-remote-logging.conf
  notify:
    - restart rsyslog

- include: cluster.yml
  when:
  - ansible_distribution|lower != "centos"
  - groups['all'] | length() > 1
