---
- name: Set Vault unseal keys
  hosts: all
  vars_prompt:
    - name: "unseal_key1_input"
      prompt: "Unseal key 1"
      private: yes
      confirm: yes
    - name: "unseal_key2_input"
      prompt: "Unseal key 2"
      private: yes
      confirm: yes
  tasks:
    - set_fact:
        unseal_key1: "{{ unseal_key1_input }}"
        unseal_key2: "{{ unseal_key2_input }}"

- name: Apply common configuration to all nodes
  hosts: all
  roles:
    - common

- name: Deploy and configure external storage client
  hosts: all
  roles:
    - { role: storage_client, when external_storage_path is defined }

- name: Deploy Vault secret system
  hosts: all
  roles:
    - { role: vault, when config_done is defined }

- name: Deploy and configure MySQL database
  hosts: all
  roles:
    - { role: db, when: config_done is defined and mysql_host is not defined and oracle_host is not defined }

- name: Deploy and configure Redis database
  hosts: all
  roles:
    - { role: redis, when: config_done is defined and redis_host is not defined }

- name: Deploy and configure the backend server
  hosts: all
  roles:
    - docker
    - { role: backend, when: config_done is defined }
    - { role: frontend, when: config_done is defined }
